import type { UpgradeCardDefinition } from './types';

export const DEFAULT_UPGRADES: UpgradeCardDefinition[] = [
  {
    id: 'fire_damage_small',
    name: 'Искра силы',
    description: 'Небольшая прибавка к прямому урону Огня.',
    rarity: 'common',
    weight: 120,
    color: '#ef4444',
    effects: [{ type: 'ability-damage-flat', abilityId: 'fire', value: 5 }],
  },
  {
    id: 'fire_damage_percent',
    name: 'Разгоревшееся пламя',
    description: 'Усиливает основной урон Огня на 25%.',
    rarity: 'rare',
    weight: 70,
    color: '#f97316',
    effects: [{ type: 'ability-damage-percent', abilityId: 'fire', value: 25 }],
  },
  {
    id: 'fire_critical_mastery',
    name: 'Критический жар',
    description: 'Повышает шанс и множитель критического урона.',
    rarity: 'epic',
    weight: 30,
    color: '#fb923c',
    effects: [
      { type: 'ability-damage-critical-chance', abilityId: 'fire', value: 35 },
      { type: 'ability-damage-critical-multiplier', abilityId: 'fire', value: 1 },
    ],
  },
  {
    id: 'fire_area_max',
    name: 'Стена пламени',
    description: 'Расширяет область основного урона до большого значения.',
    rarity: 'legendary',
    weight: 8,
    color: '#dc2626',
    effects: [
      { type: 'ability-damage-target-type', abilityId: 'fire', value: { type: 'area-enemies', count: 0, areaHeightPercent: 50 } },
      { type: 'ability-damage-area-height', abilityId: 'fire', value: 50 },
    ],
  },
  {
    id: 'lightning_extra_targets',
    name: 'Цепной разряд',
    description: 'Добавляет Молнии несколько дополнительных целей.',
    rarity: 'rare',
    weight: 65,
    color: '#eab308',
    effects: [
      { type: 'ability-damage-target-type', abilityId: 'lightning', value: { type: 'random-enemies', count: 3, areaHeightPercent: 0 } },
      { type: 'ability-damage-target-count', abilityId: 'lightning', value: 3 },
    ],
  },
  {
    id: 'lightning_fire_source',
    name: 'Плазменный разряд',
    description: 'Меняет источник урона Молнии на огненный.',
    rarity: 'epic',
    weight: 25,
    color: '#f59e0b',
    effects: [{ type: 'ability-damage-source', abilityId: 'lightning', value: 'fire' }],
  },
  {
    id: 'ice_slow_small',
    name: 'Лёгкий мороз',
    description: 'Небольшое усиление замедления и его длительности.',
    rarity: 'common',
    weight: 115,
    color: '#60a5fa',
    effects: [
      { type: 'ability-slow-percent', abilityId: 'ice', value: 5 },
      { type: 'ability-slow-duration-flat', abilityId: 'ice', value: 0.5 },
    ],
  },
  {
    id: 'ice_slow_duration_percent',
    name: 'Долгая зима',
    description: 'Увеличивает длительность замедления на 50%.',
    rarity: 'rare',
    weight: 55,
    color: '#3b82f6',
    effects: [{ type: 'ability-slow-duration-percent', abilityId: 'ice', value: 50 }],
  },
  {
    id: 'ice_slow_targets',
    name: 'Точный холод',
    description: 'Переводит замедление на ограниченное число ближайших целей.',
    rarity: 'epic',
    weight: 24,
    color: '#2563eb',
    effects: [
      { type: 'ability-slow-target-type', abilityId: 'ice', value: { type: 'nearest-enemies', count: 1, areaHeightPercent: 0 } },
      { type: 'ability-slow-target-count', abilityId: 'ice', value: 5 },
    ],
  },
  {
    id: 'ice_slow_area_max',
    name: 'Абсолютный холод',
    description: 'Переводит замедление в область максимальной высоты.',
    rarity: 'legendary',
    weight: 6,
    color: '#1d4ed8',
    effects: [
      { type: 'ability-slow-target-type', abilityId: 'ice', value: { type: 'area-enemies', count: 0, areaHeightPercent: 50 } },
      { type: 'ability-slow-area-height', abilityId: 'ice', value: 100 },
    ],
  },
  {
    id: 'shield_heal_small',
    name: 'Перевязка',
    description: 'Небольшая плоская прибавка к лечению.',
    rarity: 'common',
    weight: 125,
    color: '#22c55e',
    effects: [{ type: 'ability-heal-flat', abilityId: 'shield', value: 5 }],
  },
  {
    id: 'shield_heal_max',
    name: 'Второе дыхание',
    description: 'Сильно увеличивает лечение способности.',
    rarity: 'legendary',
    weight: 7,
    color: '#16a34a',
    effects: [{ type: 'ability-heal-percent', abilityId: 'shield', value: 100 }],
  },
  {
    id: 'add_periodic_small',
    name: 'Слабое горение',
    description: 'Добавляет Молнии небольшой периодический урон с явно заданными параметрами.',
    rarity: 'common',
    weight: 100,
    color: '#111827',
    effects: [{
      type: 'ability-add-periodic-damage',
      abilityId: 'lightning',
      value: {
        chancePercent: 10,
        amount: 1,
        duration: 1,
        criticalChancePercent: 0,
        criticalMultiplier: 0,
        visualColor: '#000000',
        target: { type: 'nearest-enemies', count: 1, areaHeightPercent: 0 },
      },
    }],
  },
  {
    id: 'add_periodic_max',
    name: 'Адское горение',
    description: 'Добавляет Огню мощный периодический эффект с параметрами до 100%.',
    rarity: 'legendary',
    weight: 5,
    color: '#991b1b',
    effects: [{
      type: 'ability-add-periodic-damage',
      abilityId: 'fire',
      value: {
        chancePercent: 100,
        amount: 200,
        duration: 10,
        criticalChancePercent: 100,
        criticalMultiplier: 3,
        visualColor: '#ff0000',
        target: { type: 'area-enemies', count: 0, areaHeightPercent: 100 },
      },
    }],
  },
  {
    id: 'add_damage_small',
    name: 'Ледяной удар',
    description: 'Добавляет Льду небольшой прямой урон.',
    rarity: 'common',
    weight: 105,
    color: '#93c5fd',
    effects: [{
      type: 'ability-add-damage',
      abilityId: 'ice',
      value: {
        amount: 1,
        damageSourceId: 'ice',
        criticalChancePercent: 0,
        criticalMultiplier: 0,
        target: { type: 'nearest-enemies', count: 1, areaHeightPercent: 0 },
      },
    }],
  },
  {
    id: 'add_damage_max',
    name: 'Кара защитника',
    description: 'Добавляет Лечению сильный прямой урон с максимальным шансом крита и большой областью.',
    rarity: 'legendary',
    weight: 4,
    color: '#f43f5e',
    effects: [{
      type: 'ability-add-damage',
      abilityId: 'shield',
      value: {
        amount: 200,
        damageSourceId: 'fire',
        criticalChancePercent: 100,
        criticalMultiplier: 3,
        target: { type: 'area-enemies', count: 0, areaHeightPercent: 100 },
      },
    }],
  },
  {
    id: 'add_slow_small',
    name: 'Остывающий пепел',
    description: 'Добавляет Огню слабое короткое замедление.',
    rarity: 'rare',
    weight: 60,
    color: '#94a3b8',
    effects: [{
      type: 'ability-add-slow',
      abilityId: 'fire',
      value: {
        slowPercent: 1,
        duration: 0.5,
        target: { type: 'nearest-enemies', count: 1, areaHeightPercent: 0 },
      },
    }],
  },
  {
    id: 'add_slow_max',
    name: 'Парализующий разряд',
    description: 'Добавляет Молнии максимальное замедление по большой области.',
    rarity: 'legendary',
    weight: 5,
    color: '#a855f7',
    effects: [{
      type: 'ability-add-slow',
      abilityId: 'lightning',
      value: {
        slowPercent: 100,
        duration: 10,
        target: { type: 'area-enemies', count: 0, areaHeightPercent: 100 },
      },
    }],
  },
  {
    id: 'add_heal_small',
    name: 'Тёплая искра',
    description: 'Добавляет Огню небольшое лечение замка.',
    rarity: 'common',
    weight: 110,
    color: '#4ade80',
    effects: [{
      type: 'ability-add-heal',
      abilityId: 'fire',
      value: {
        amount: 1,
        target: { type: 'castle', count: 0, areaHeightPercent: 0 },
      },
    }],
  },
  {
    id: 'add_heal_large',
    name: 'Грозовое восстановление',
    description: 'Добавляет Молнии сильное лечение замка.',
    rarity: 'epic',
    weight: 20,
    color: '#22c55e',
    effects: [{
      type: 'ability-add-heal',
      abilityId: 'lightning',
      value: {
        amount: 100,
        target: { type: 'castle', count: 0, areaHeightPercent: 0 },
      },
    }],
  },

  {
    id: 'ice_added_damage_boost',
    name: 'Закалённый осколок',
    description: 'Усиливает прямой урон, который Лёд получил от других карточек.',
    rarity: 'rare',
    weight: 55,
    color: '#7dd3fc',
    effects: [
      { type: 'ability-damage-flat', abilityId: 'ice', value: 8 },
      { type: 'ability-damage-percent', abilityId: 'ice', value: 25 },
    ],
  },
  {
    id: 'ice_added_damage_critical',
    name: 'Хрупкий лёд',
    description: 'Добавляет критические параметры прямому урону Льда, даже если урон был получен карточкой.',
    rarity: 'epic',
    weight: 28,
    color: '#38bdf8',
    effects: [
      { type: 'ability-damage-critical-chance', abilityId: 'ice', value: 20 },
      { type: 'ability-damage-critical-multiplier', abilityId: 'ice', value: 1 },
    ],
  },
  {
    id: 'ice_added_damage_targets',
    name: 'Ледяная дробь',
    description: 'Добавляет дополнительные цели прямому урону Льда.',
    rarity: 'rare',
    weight: 50,
    color: '#0ea5e9',
    effects: [{ type: 'ability-damage-target-count', abilityId: 'ice', value: 1 }],
  },
  {
    id: 'lightning_added_periodic_boost',
    name: 'Затяжной разряд',
    description: 'Усиливает периодический урон Молнии, который мог быть добавлен другой карточкой.',
    rarity: 'rare',
    weight: 52,
    color: '#fde047',
    effects: [
      { type: 'ability-periodic-damage-flat', abilityId: 'lightning', value: 4 },
      { type: 'ability-periodic-duration-flat', abilityId: 'lightning', value: 1.5 },
      { type: 'ability-periodic-chance', abilityId: 'lightning', value: 20 },
    ],
  },
  {
    id: 'lightning_added_periodic_critical',
    name: 'Перегрузка разряда',
    description: 'Улучшает критические параметры периодического урона Молнии.',
    rarity: 'epic',
    weight: 26,
    color: '#facc15',
    effects: [
      { type: 'ability-periodic-critical-chance', abilityId: 'lightning', value: 20 },
      { type: 'ability-periodic-critical-multiplier', abilityId: 'lightning', value: 1 },
    ],
  },
  {
    id: 'lightning_added_periodic_targets',
    name: 'Блуждающий ток',
    description: 'Добавляет цели периодическому урону Молнии.',
    rarity: 'rare',
    weight: 48,
    color: '#eab308',
    effects: [{ type: 'ability-periodic-target-count', abilityId: 'lightning', value: 1 }],
  },
  {
    id: 'fire_added_slow_boost',
    name: 'Тяжёлый пепел',
    description: 'Усиливает замедление Огня, даже если замедление было добавлено другой карточкой.',
    rarity: 'rare',
    weight: 54,
    color: '#a8a29e',
    effects: [
      { type: 'ability-slow-percent', abilityId: 'fire', value: 10 },
      { type: 'ability-slow-duration-flat', abilityId: 'fire', value: 1 },
    ],
  },
  {
    id: 'fire_added_slow_targets',
    name: 'Пепельная волна',
    description: 'Добавляет дополнительные цели замедлению Огня.',
    rarity: 'epic',
    weight: 25,
    color: '#78716c',
    effects: [{ type: 'ability-slow-target-count', abilityId: 'fire', value: 2 }],
  },
  {
    id: 'fire_added_heal_boost',
    name: 'Живительное тепло',
    description: 'Усиливает лечение Огня, которое могло быть добавлено другой карточкой.',
    rarity: 'rare',
    weight: 56,
    color: '#4ade80',
    effects: [
      { type: 'ability-heal-flat', abilityId: 'fire', value: 5 },
      { type: 'ability-heal-percent', abilityId: 'fire', value: 25 },
    ],
  },
  {
    id: 'shield_added_damage_boost',
    name: 'Ответный импульс',
    description: 'Усиливает прямой урон Лечения, если он был добавлен карточкой.',
    rarity: 'epic',
    weight: 22,
    color: '#fb7185',
    effects: [
      { type: 'ability-damage-percent', abilityId: 'shield', value: 25 },
      { type: 'ability-damage-critical-chance', abilityId: 'shield', value: 15 },
    ],
  },
];
